M48
; DRILL file {KiCad 7.0.6} date Thu Nov 30 14:41:18 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-30T14:41:18-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
%
G90
G05
T1
X11.048Y-6.434
T2
X10.8872Y-5.8038
X10.9896Y-5.8038
T0
M30
